# Generated by Django 3.1.5 on 2021-01-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='상품 이름', max_length=50)),
                ('image', models.ImageField(help_text='상품 대표 이미지', upload_to='product_main_image/%Y/%m/%d/')),
                ('desc', models.TextField(blank=True, help_text='상품 설명')),
                ('sell_price', models.IntegerField(default=0, help_text='현재 판매가')),
                ('stock', models.IntegerField(help_text='상품 재고')),
                ('sales_count', models.IntegerField(default=0, help_text='판매 수량')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='상품 이미지', upload_to='product_images/%Y/%m/%d/')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
        ),
    ]
